/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 electrical_transformer.glb 
Author: abass20 (https://sketchfab.com/abass20)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/electrical-transformer-615fe4b367314a72b7dffb8ec791f575
Title: Electrical Transformer
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model() {
  const { nodes, materials } = useGLTF("./models/electrical_transformer.glb");
  return (
    <group dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={
            //@ts-ignore
            nodes.Base_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
          scale={[1, 2, 2]}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.MainBody_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
          position={[100, 180, 0]}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.FrontCoolers_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.Fans_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.OilTank_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.SideCoolers_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.Panel_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
          position={[98.05, 176.303, -190.023]}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.Coil001_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
          position={[138.888, 416.402, 138.922]}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.Coil_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
          position={[66.463, 416.402, 138.922]}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.TopPorts_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
        />
        <mesh
          geometry={
            //@ts-ignore
            nodes.ElectricalRack_ElectricalTransformer01MAT_0.geometry
          }
          material={materials.ElectricalTransformer01MAT}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/electrical_transformer.glb");
