/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 trans.glb 
Author: ahmagh2e (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/power-transformer-building-roof-top-electricity-3d4e139c064143ee891caa01dc3c0213
Title: Power transformer Building roof top Electricity
*/

import { useGLTF } from "@react-three/drei";

export function Model() {
  const { nodes, materials } = useGLTF("./models/trans.glb");
  return (
    <group dispose={null} scale={[0.5, 0.5, 0.5]}>
      <mesh
        //@ts-ignore
        geometry={nodes.Object_2.geometry}
        material={materials["default"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/trans.glb");
